name: Tests

permissions: "read-all"

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
          stable: false
      - name: Run golang compilation check
        run: make test
      - name: Build docker image
        run: make docker
